import org.jetbrains.kotlin.gradle.dsl.JvmTarget

apply plugin: 'com.android.application'

//
// build.gradle in TeamCode
//
// Most of the definitions for building your module reside in a common, shared
// file 'build.common.gradle'. Being factored in this way makes it easier to
// integrate updates to the FTC into your code. If you really need to customize
// the build definitions, you can place those customizations in this file, but
// please think carefully as to whether such customizations are really necessary
// before doing so.

// Custom definitions may go here

// Include common definitions from above.
apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'
// Kotlin Plugin, necessary for kotlin development
apply plugin: 'org.jetbrains.kotlin.android'


android {
    namespace = 'org.firstinspires.ftc.teamcode'

    compileSdk = 34

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
            freeCompilerArgs.add("-Xjvm-expose-boxed")
        }
    }

    defaultConfig {
        minSdk 24
    }

    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

repositories {
    // Dairy Foundation repository
    maven { url 'https://repo.dairy.foundation/releases/'}

    // Panels bylazar repository
    maven { url = "https://mymaven.bylazar.com/releases" }
}

dependencies {
    // FTC Robot Controller
    implementation project(':FtcRobotController')
    annotationProcessor files('lib/OpModeAnnotationProcessor.jar')

    // Solvers lib
    implementation "org.solverslib:core:0.3.5" // core

    // Pedro Pathing
    implementation 'com.pedropathing:revhub:3.0.0'
    implementation 'com.pedropathing:tuning:1.0.0'

    // Panels
    implementation "com.bylazar:fullpanels:1.0.13"

    // PSI Kit
    implementation 'org.psilynx.psikit:core:0.2.0'
    implementation 'org.psilynx.psikit:ftc:0.2.0'
}
